// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var React           = require("react");
var ReasonReact     = require("reason-react/lib/js/src/reasonReact.js");
var Board$TicTacToe = require("./Board.js");

var component = ReasonReact.statelessComponent("Game");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "game"
                }, React.createElement("div", {
                      className: "game-board"
                    }, ReasonReact.element(/* None */0, /* None */0, Board$TicTacToe.make(/* array */[]))), React.createElement("div", {
                      className: "game-info"
                    }, React.createElement("div", undefined), React.createElement("ol", undefined)));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
