// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe     = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact    = require("reason-react/lib/js/src/reasonReact.js");
var Game$TicTacToe = require("./Game.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Game$TicTacToe.make(/* array */[])), "root");

/*  Not a pure module */
