// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Square");

function make(value, toggleSquare, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("button", {
                  className: "square",
                  onClick: toggleSquare
                }, value);
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
